site_name: ETL
site_url: https://supabase.github.io/etl
site_description: Build Postgres replication apps in Rust
copyright: Copyright &copy; Supabase
repo_name: supabase/etl
repo_url: https://github.com/supabase/etl
edit_uri: edit/main/docs/

nav:
  - Home:
      - index.md
  - Tutorials:
      - Tutorials: tutorials/index.md
      - Getting started: tutorials/getting-started.md
  - Guides:
      - Guides: guides/index.md
      - Database setup: guides/database-setup.md
  - Design:
      - Design: design/index.md
      - ETL crate design: design/etl-crate-design.md
  - Reference:
      - Reference: reference/index.md

theme:
  name: "material"
  favicon: "assets/favicon.ico"
  logo: "assets/etl.svg"
  homepage: https://supabase.github.io/etl
  features:
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - toc.follow
    - search.suggest
    - search.share
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: green
      accent: green

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: green
      accent: green
  font:
    text: "IBM Plex Sans"
    code: Roboto Mono
  icon:
    repo: material/github
    edit: material/pencil
    view: material/eye

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/supabase
      name: Supabase on Twitter
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/r/supabase
      name: Supabase on Reddit
    - icon: fontawesome/brands/github
      link: https://github.com/supabase/etl
      name: ETL on GitHub

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - pymdownx.highlight:
      linenums: true
      guess_lang: false
      use_pygments: true
      pygments_style: default
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.keys
  - admonition
  - tables
  - footnotes

plugins:
  - search
